[package]
name = "cluConstData"
version = "1.2.6"
authors = ["Denis Kotlyarov (Денис Котляров) <denis2005991@gmail.com>"]
repository = "https://github.com/clucompany/cluConstData.git"
edition = "2018"

license = "Apache-2.0"
readme = "README.md"

description = "Combining any persistent data with each other at compile time."
keywords = ["const_data", "combination_const_data", "concat_const_data", "cluConstData", "clucompany"]
categories = ["development-tools::ffi"]

[dependencies]
cluFullTransmute = "1.0.1"